import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import type { CompanyEvaluation, CompanySummary } from "@sv/contracts/generated";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { DashboardApp } from "./app";

const aether: CompanySummary = { slug: "aether", company: "Aether Robotics", stage: "Seed", submissionDate: "2026-07-19T12:00:00Z", overallScore: 82, categoryScores: { home: null, idea: 83, market: 80, financial: 82, management: 84 } };
const harbor: CompanySummary = { slug: "harbor", company: "Harborloop", stage: "Pre-seed", submissionDate: "2026-07-18T12:00:00Z", overallScore: 68, categoryScores: { home: null, idea: 71, market: null, financial: 65, management: 68 } };
function evaluation(summary: CompanySummary, portfolioScore: number | null = null): CompanyEvaluation {
  const item = (id: string, title: string, score: number | null) => ({ id, category: id.split(".")[0] as "home" | "idea" | "market" | "financial" | "management", title, score, confidence: 80, assessment: `${summary.company} assessment.`, positiveArguments: ["Supported positive."], negativeArguments: ["Known risk."], evidence: [{ kind: "fact" as const, documentId: "submission", text: "Useful submitted evidence." }], missingInformation: score === null ? ["Portfolio data was not provided."] : [], sourceReferences: [{ kind: "fact" as const, documentId: "submission", text: "Hidden technical source reference." }], validationErrors: [] });
  const doc = (category: "home" | "idea" | "market" | "financial" | "management", items: ReturnType<typeof item>[]) => ({ schemaVersion: 1 as const, registryVersion: 1 as const, company: summary.company, slug: summary.slug, category, generatedAt: summary.submissionDate, sourceDocuments: [], items, validationErrors: [] });
  const diligenceItem = { ...item("home.missing_information", "What important information is missing?", null), assessment: "Obtain signed contracts, deployment uptime data, and independent competitor comparisons." };
  return { companyId: `${summary.slug}-id`, company: summary.company, slug: summary.slug, stage: summary.stage, submissionDate: summary.submissionDate, investment: { amount: null, currency: null, equityPercentage: null, preMoneyValuation: null, postMoneyValuation: null, impliedValuation: null, useOfFunds: [] }, categories: { home: doc("home", [item("home.company_name", "What is the company name?", null), item("home.company_idea", "What is the company idea?", null), item("home.founders", "Who are the founders?", null), diligenceItem]), idea: doc("idea", [item("idea.uniqueness", "How unique is the company idea?", summary.categoryScores.idea)]), market: doc("market", [item("market.portfolio_fit", "Does the company fit the VC portfolio?", portfolioScore)]), financial: doc("financial", [item("financial.current_revenue", "What is the current revenue?", summary.categoryScores.financial)]), management: doc("management", [item("management.academic_background", "How strong is the academic background?", summary.categoryScores.management)]) }, categoryScores: summary.categoryScores, overallScore: summary.overallScore, validationErrors: [] } as CompanyEvaluation;
}
const api = vi.hoisted(() => ({ getCompanies: vi.fn(), getCompany: vi.fn() }));
vi.mock("./lib/api", async () => ({ ...(await vi.importActual<typeof import("./lib/api")>("./lib/api")), getCompanies: api.getCompanies, getCompany: api.getCompany }));
describe("DashboardApp", () => {
  beforeEach(() => { window.history.replaceState({}, "", "/companies/aether/home"); api.getCompanies.mockResolvedValue({ companies: [aether, harbor], registryVersion: 1 }); api.getCompany.mockImplementation((slug: string) => Promise.resolve(evaluation(slug === "harbor" ? harbor : aether))); });
  it("renders Company record entries as concise facts without evaluation metadata", async () => { render(<DashboardApp />); expect(await screen.findByRole("heading", { name: "Aether Robotics" })).toBeInTheDocument(); const title = screen.getByRole("heading", { name: "What is the company name?" }); const details = title.closest("details"); const summary = title.closest("summary"); expect(details).not.toHaveAttribute("open"); expect(within(details!).queryByText("Criterion")).not.toBeInTheDocument(); expect(within(details!).queryByLabelText(/score/i)).not.toBeInTheDocument(); expect(within(details!).queryByText(/confidence/i)).not.toBeInTheDocument(); expect(summary).not.toBeNull(); fireEvent.click(summary!); expect(details).toHaveAttribute("open"); expect(within(details!).queryByRole("heading", { name: "Recorded value" })).not.toBeInTheDocument(); expect(within(details!).getByText("Aether Robotics assessment.")).toBeInTheDocument(); expect(within(details!).queryByRole("heading", { name: "Positive arguments" })).not.toBeInTheDocument(); expect(within(details!).queryByRole("heading", { name: "Evidence notes" })).not.toBeInTheDocument(); expect(within(details!).queryByText("Useful submitted evidence.")).not.toBeInTheDocument(); expect(within(details!).queryByText("Hidden technical source reference.")).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("link", { name: /market/i })); expect(await screen.findByRole("heading", { name: "Market evaluation" })).toBeInTheDocument(); const portfolioDetails = screen.getByText("Does the company fit the VC portfolio?").closest("details"); expect(portfolioDetails).not.toHaveAttribute("open"); expect(within(portfolioDetails!).getByLabelText("Criterion score: unavailable")).toBeInTheDocument(); });
  it("shows only non-redundant fact evidence as source excerpts", async () => { render(<DashboardApp />); await screen.findByRole("heading", { name: "Aether Robotics" }); fireEvent.click(screen.getByRole("link", { name: /^idea/i })); const details = (await screen.findByText("How unique is the company idea?")).closest("details"); fireEvent.click(details!.querySelector("summary")!); expect(within(details!).getByRole("heading", { name: "Source excerpts" })).toBeInTheDocument(); expect(within(details!).getByText("Useful submitted evidence.")).toBeInTheDocument(); });
  it("omits source excerpts when the evidence merely repeats the assessment", async () => { const value = evaluation(aether); const item = value.categories.idea!.items[0]; item.evidence = [{ kind: "fact", documentId: "submission", text: item.assessment }]; api.getCompany.mockResolvedValue(value); render(<DashboardApp />); await screen.findByRole("heading", { name: "Aether Robotics" }); fireEvent.click(screen.getByRole("link", { name: /^idea/i })); const details = (await screen.findByText("How unique is the company idea?")).closest("details"); fireEvent.click(details!.querySelector("summary")!); expect(within(details!).queryByRole("heading", { name: "Source excerpts" })).not.toBeInTheDocument(); });
  it("shows full German-formatted Aether terms in the dashboard metadata", async () => { api.getCompany.mockResolvedValue({ ...evaluation(aether), investment: { amount: 100000, currency: "EUR", equityPercentage: 1, preMoneyValuation: 9900000, postMoneyValuation: 10000000, impliedValuation: 10000000, useOfFunds: [] } }); render(<DashboardApp />); expect(await screen.findByLabelText("Investment terms: 100.000 € for 1%")).toBeInTheDocument(); });
  it("renders score strength with a matching color tone and progress bar", async () => { render(<DashboardApp />); await screen.findByRole("heading", { name: "Aether Robotics" }); const badge = document.querySelector<HTMLElement>(".sv-score-badge--strong"); expect(badge).not.toBeNull(); expect(badge?.querySelector<HTMLElement>(".sv-score-badge__fill")).toHaveStyle({ width: "82%" }); });
  it("uses the answered Home assessment for diligence priorities", async () => { render(<DashboardApp />); const heading = await screen.findByRole("heading", { name: "Diligence priorities" }); const priorityBlock = heading.closest("article"); expect(within(priorityBlock!).getByText("Obtain signed contracts, deployment uptime data, and independent competitor comparisons.")).toBeInTheDocument(); expect(screen.queryByRole("heading", { name: "Missing information", level: 2 })).not.toBeInTheDocument(); });
  it("labels unavailable investment terms without inventing a currency", async () => { render(<DashboardApp />); expect(await screen.findByLabelText("Investment terms: Terms unavailable")).toBeInTheDocument(); });
  it("renders all five category views for the fixture-backed company data", async () => {
    render(<DashboardApp />);

    expect(await screen.findByRole("heading", { name: "Aether Robotics" })).toBeInTheDocument();
    expect(screen.getByText("Company overview")).toBeInTheDocument();

    for (const [label, heading] of [
      ["idea", "Idea evaluation"],
      ["market", "Market evaluation"],
      ["financial", "Financials evaluation"],
      ["management", "Management evaluation"],
    ] as const) {
      fireEvent.click(screen.getByRole("link", { name: new RegExp(`^${label}`, "i") }));
      expect(await screen.findByRole("heading", { name: heading })).toBeInTheDocument();
    }
  });
  it("clears the previous company before displaying a newly selected one", async () => { render(<DashboardApp />); expect((await screen.findAllByText("Aether Robotics assessment.")).length).toBeGreaterThan(0); fireEvent.change(screen.getByLabelText("Company under review"), { target: { value: "harbor" } }); await waitFor(() => expect(screen.queryAllByText("Aether Robotics assessment.")).toHaveLength(0)); expect((await screen.findAllByText("Harborloop assessment.")).length).toBeGreaterThan(0); });
  it("rejects a cross-company API response visibly", async () => { api.getCompany.mockResolvedValue(evaluation(harbor)); render(<DashboardApp />); expect(await screen.findByText(/identity check/i)).toBeInTheDocument(); });
});
